[project]
name = "dungeon-crawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.9.0",
    "pygame>=2.6.1",
    "pyinstaller>=6.16.0",
    "pylint>=4.0.2",
    "pytest>=8.4.2",
]
